export default {
  ID: "_id",
  ASCENDING: "asc",
  DESCENDING: "desc",
  STRING: "string",
  FUNCTION: "function",
  INCLUDE: "include",
  PRODUCTION: "production",
  ROOT: "root",
  OPEN: "open",
  CLOSE: "close",
  WIDTH: "width",
  MARGIN: "margin",
  NAVBAR_WIDTH: `calc(100% - 240px)`,
  PHP: "PHP",
  CONFIRM: "Are you sure?",
  PENDING: "pending",
  CANCELLED: "cancelled",
  NOT_PAID: "not paid",
  ACTIVE: "active",
  INACTIVE: "Inactive",
  YES: "Yes",
  NO: "No",
  LOGOUT: "Logout successful!",
  NUMBER: {
    NEGATIVE_ONE: -1,
    ZERO: 0,
    POINT_TWO: 0.2,
    POINT_FIVE: 0.5,
    ONE: 1,
    ONE_POINT_FIVE: 1.5,
    TWO: 2,
    THREE: 3,
    FOUR: 4,
    FIVE: 5,
    SIX: 6,
    SEVEN: 7,
    SEVEN_POINT_FIVE: 7.5,
    EIGHT: 8,
    NINE: 9,
    TEN: 10,
    TWELVE: 12,
    FOURTEEN: 14,
    SIXTEEN: 16,
    TWENTY: 20,
    TWENTY_TWO: 22,
    THIRTY: 30,
    THIRTY_TWO: 32,
    FORTY: 40,
    FIFTY: 50,
    SIXTY: 60,
    SEVENTY_FIVE: 75,
    EIGHTY: 80,
    HUNDRED: 100,
    HUNDRED_FIFTY: 150,
    TWO_HUNDRED_FORTY: 240,
    FOUR_HUNDRED: 400,
    FIVE_HUNDRED_FIFTY: 550,
    SIX_HUNDRED: 600,
    SEVEN_HUNDRED: 700,
    THOUSAND_TWO_HUNDRED: 1200,
    FIVE_THOUSAND: 5000,
    TEN_THOUSAND: 10000,
  },
};
