export default {
  LOGIN_ROUTE: "/login",
  LOGOUT_ROUTE: "/logout",
  FORGOT_PASSWORD: "/Forgotpassword",
  RESET_PASSWORD: "/password/reset/:id",
  UPDATE_PASSWORD: "/updatePassword/:id",
  USERS_ROUTE: "users",
  USER_ID_ROUTE: "user/:id",
  EDIT_USER_ID: "user/edit/:id",
  NOTES_ROUTE: "notes",
  NOTE_ID_ROUTE: "note/:id",
  EDIT_NOTE_ID: "note/edit/:id",
  CAMERAS_ROUTE: "cameras",
  CAMERA_ID_ROUTE: "camera/:id",
  EDIT_CAMERA_ID: "camera/edit/:id",
  TRANSACTIONS_ROUTE: "transactions",
  TRANSACTION_ID_ROUTE: "transaction/:id",
  EDIT_TRANSACTION_ID: "transaction/edit/:id",
  COMMENTS_ROUTE: "comments",
  COMMENT_ID_ROUTE: "comment/:id",
  EDIT_COMMENT_ID: "comment/edit/:id",
};
